

import type { StoredUser } from '../types';

const seedUsers: StoredUser[] = [
    // --- Hyderabad, Telangana, India ---
    {
        email: 'owner1@apollothy.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Sanjay Reddy',
        displayName: 'Sanjay R.',
        storeName: 'Apollo Pharmacy - Jubilee Hills',
        address: 'Rd Number 36, Jubilee Hills, Hyderabad, Telangana 500033',
        location: { lat: 17.4300, lng: 78.4012 },
        inventory: [
            { name: 'Paracetamol 650mg', brands: ['Dolo 650', 'Crocin Advance', 'Calpol'], stock: 200 },
            { name: 'Azithromycin 500mg', brands: ['Azee 500', 'Azithral 500'], stock: 75 },
            { name: 'Montelukast + Levocetirizine', brands: ['Montair-LC', 'Montek LC'], stock: 110 },
            { name: 'Amoxicillin 500mg', brands: ['Moxikind-CV 625'], stock: 0 },
            { name: 'Vitamin C + Zinc', brands: ['Limcee', 'Celin 500'], stock: 150 },
            { name: 'Telmisartan 40mg', brands: ['Telma 40', 'Cresar 40'], stock: 85 },
            { name: 'Amlodipine 5mg', brands: ['Amlokind 5', 'Amlopres 5'], stock: 120 },
        ],
    },
    {
        email: 'owner2@medplus.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Anjali Rao',
        displayName: 'Anjali',
        storeName: 'MedPlus - Gachibowli',
        address: 'DLF Cyber City, Gachibowli, Hyderabad, Telangana 500032',
        location: { lat: 17.4483, lng: 78.3614 },
        inventory: [
            { name: 'Paracetamol 650mg', brands: ['Dolo 650', 'P-650'], stock: 180 },
            { name: 'Atorvastatin 10mg', brands: ['Atorva 10', 'Lipikind'], stock: 90 },
            { name: 'Metformin 500mg', brands: ['Glycomet 500 SR', 'Gluconorm'], stock: 120 },
            { name: 'Aspirin 75mg', brands: ['Ecosprin 75', 'Disprin'], stock: 250 },
            { name: 'Domperidone + Pantoprazole', brands: ['Pan-D', 'Pantocid DSR'], stock: 60 },
            { name: 'Glimepiride 1mg', brands: ['Amaryl 1', 'Glimestar 1'], stock: 50 },
        ],
    },
    {
        email: 'owner3@wellness.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Vikram Singh',
        displayName: 'Vik S.',
        storeName: 'Wellness Forever - Hitech City',
        address: 'Inorbit Mall Road, Hitech City, Hyderabad, Telangana 500081',
        location: { lat: 17.4262, lng: 78.3842 },
        inventory: [
            { name: 'Ibuprofen 400mg', brands: ['Ibugesic 400', 'Brufen 400'], stock: 130 },
            { name: 'Rosuvastatin 10mg', brands: ['Rosuvas 10', 'Roseday 10'], stock: 0 },
            { name: 'Cholecalciferol 60000 IU', brands: ['Uprise-D3 60K', 'Calcirol Sachet'], stock: 300 },
            { name: 'Cetirizine 10mg', brands: ['Okacet', 'Cetzine'], stock: 280 },
            { name: 'Omeprazole 20mg', brands: ['Omez', 'Ocid 20'], stock: 95 },
        ],
    },
    {
        email: 'owner4@balajimed.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Priya Sharma',
        displayName: 'Priya',
        storeName: 'Balaji Medical & General Store - Secunderabad',
        address: 'M.G. Road, Secunderabad, Telangana 500003',
        location: { lat: 17.4399, lng: 78.4983 },
        inventory: [
            { name: 'Paracetamol 500mg', brands: ['Calpol 500', 'Crocin Pain Relief'], stock: 400 },
            { name: 'Cough Syrup', brands: ['Benadryl', 'Grilinctus'], stock: 100 },
            { name: 'Antacid Gel', brands: ['Digene', 'Gelusil MPS'], stock: 150 },
            { name: 'Pain Relief Gel', brands: ['Volini', 'Moov'], stock: 200 },
            { name: 'Ranitidine 150mg', brands: ['Zantac', 'Rantac 150'], stock: 125 },
        ],
    },
     {
        email: 'owner5@lifecare.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Rohan Mehta',
        displayName: 'Rohan M.',
        storeName: 'LifeCare Pharmacy - Banjara Hills',
        address: 'Road No. 1, Banjara Hills, Hyderabad, Telangana 500034',
        location: { lat: 17.4150, lng: 78.4485 },
        inventory: [
            { name: 'Calcium + Vitamin D3', brands: ['Shelcal 500', 'Gemcal'], stock: 180 },
            { name: 'B-Complex with Vitamin C', brands: ['Becosules Z', 'Supradyn'], stock: 220 },
            { name: 'Iron + Folic Acid', brands: ['Feronia-XT', 'Fefol-Z'], stock: 0 },
            { name: 'Losartan 50mg', brands: ['Losar 50', 'Losakind 50'], stock: 70 },
            { name: 'Vildagliptin 50mg', brands: ['Galvus 50', 'Jalra 50'], stock: 40 },
        ],
    },
    {
        email: 'owner6@hetero.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Kavita Iyer',
        displayName: 'Kavita',
        storeName: 'Hetero Pharmacy - Kukatpally',
        address: 'KPHB Colony, Kukatpally, Hyderabad, Telangana 500072',
        location: { lat: 17.4848, lng: 78.4017 },
        inventory: [
            { name: 'Ofloxacin 200mg', brands: ['Oflox 200', 'Zanocin 200'], stock: 65 },
            { name: 'Ciprofloxacin 500mg', brands: ['Cifran 500', 'Ciplox 500'], stock: 80 },
            { name: 'Metronidazole 400mg', brands: ['Flagyl 400', 'Metrogyl 400'], stock: 115 },
            { name: 'Diclofenac Gel', brands: ['Voveran Gel', 'Relaxyl'], stock: 150 },
            { name: 'Paracetamol 650mg', brands: ['Dolo 650'], stock: 300 },
        ],
    },
    {
        email: 'owner7@medplus2.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Arjun Desai',
        displayName: 'Arjun D.',
        storeName: 'MedPlus - Madhapur',
        address: 'Image Gardens Road, Madhapur, Hyderabad, Telangana 500081',
        location: { lat: 17.4475, lng: 78.3918 },
        inventory: [
            { name: 'Atorvastatin 20mg', brands: ['Atorva 20', 'Storvas 20'], stock: 100 },
            { name: 'Clopidogrel 75mg', brands: ['Clopitab 75', 'Deplatt 75'], stock: 130 },
            { name: 'Metoprolol 25mg', brands: ['Metolar XR 25', 'Starpress-XL 25'], stock: 90 },
            { name: 'Fexofenadine 120mg', brands: ['Allegra 120', 'Fexova 120'], stock: 0 },
            { name: 'Domperidone + Pantoprazole', brands: ['Pan-D', 'Pantop D'], stock: 150 },
        ],
    },
    {
        email: 'owner8@apollothy2.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Sunita Patil',
        displayName: 'Sunita',
        storeName: 'Apollo Pharmacy - Begumpet',
        address: 'Opposite Shoppers Stop, Begumpet, Hyderabad, Telangana 500016',
        location: { lat: 17.4431, lng: 78.4671 },
        inventory: [
            { name: 'Amoxicillin + Clavulanic Acid 625mg', brands: ['Augmentin 625 Duo'], stock: 140 },
            { name: 'Doxycycline 100mg', brands: ['Doxy-1 L-DR Forte'], stock: 70 },
            { name: 'Sertraline 50mg', brands: ['Zoloft', 'Sertima 50'], stock: 45 },
            { name: 'Escitalopram 10mg', brands: ['Nexito 10', 'Cipralex'], stock: 55 },
            { name: 'Olanzapine 5mg', brands: ['Oleanz 5', 'Zyprexa'], stock: 30 },
        ],
    },
    {
        email: 'owner9@sanjeevani.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Rajesh Kumar',
        displayName: 'Rajesh',
        storeName: 'Sanjeevani Medical Hall - Ameerpet',
        address: 'Ameerpet X Road, Hyderabad, Telangana 500016',
        location: { lat: 17.4375, lng: 78.4481 },
        inventory: [
            { name: 'Pain Relief Spray', brands: ['Volini Spray', 'Moov Spray'], stock: 180 },
            { name: 'Antiseptic Liquid', brands: ['Dettol', 'Savlon'], stock: 250 },
            { name: 'Band-Aids', brands: ['Hansaplast', 'Band-Aid'], stock: 500 },
            { name: 'ORS Powder', brands: ['Electral', 'ORSL'], stock: 350 },
            { name: 'Ibuprofen 200mg', brands: ['Combiflam', 'Ibugesic 200'], stock: 200 },
        ],
    },
    {
        email: 'owner10@noble.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Meera Gupta',
        displayName: 'Meera G.',
        storeName: 'Noble Medicals - Kondapur',
        address: 'Botanical Garden Rd, Kondapur, Hyderabad, Telangana 500084',
        location: { lat: 17.4665, lng: 78.3614 },
        inventory: [
            { name: 'Levocetirizine 5mg', brands: ['Lecope', 'Vozet 5'], stock: 180 },
            { name: 'Ambroxol + Guaifenesin + Terbutaline Syrup', brands: ['Grilinctus-BM', 'Ascoril LS'], stock: 90 },
            { name: 'Nimesulide 100mg', brands: ['Nise', 'Nimulid'], stock: 0 },
            { name: 'Serratiopeptidase', brands: ['Emanzen-D', 'Seradic-AP'], stock: 110 },
            { name: 'Methylcobalamin', brands: ['Nurokind-OD', 'Me-12'], stock: 150 },
        ],
    },
    {
        email: 'owner11@citycentral.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Aditya Varma',
        displayName: 'Aditya',
        storeName: 'City Central Pharmacy - Nampally',
        address: 'Nampally Station Road, Hyderabad, Telangana 500001',
        location: { lat: 17.3916, lng: 78.4608 },
        inventory: [
            { name: 'Insulin Glargine', brands: ['Lantus', 'Basalog'], stock: 20 },
            { name: 'Insulin Aspart', brands: ['Novorapid', 'Fiasp'], stock: 25 },
            { name: 'Thyroxine 50mcg', brands: ['Thyronorm 50', 'Eltroxin 50'], stock: 100 },
            { name: 'Warfarin 2mg', brands: ['Warf 2', 'Coumadin'], stock: 35 },
            { name: 'Heparin Injection', brands: [''], stock: 15 },
        ],
    },
    {
        email: 'owner12@dailyplus.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Sneha Choudhary',
        displayName: 'Sneha',
        storeName: 'DailyPlus Pharmacy - Manikonda',
        address: 'OU Colony, Manikonda, Hyderabad, Telangana 500089',
        location: { lat: 17.4140, lng: 78.3941 },
        inventory: [
            { name: 'Mupirocin Ointment', brands: ['Bactroban', 'T-Bact'], stock: 80 },
            { name: 'Clotrimazole Cream', brands: ['Candid Cream', 'Clocip'], stock: 120 },
            { name: 'Betamethasone Cream', brands: ['Betnovate-N', 'Diprolene'], stock: 60 },
            { name: 'Silver Sulfadiazine Cream', brands: ['Silverex', 'Burn-Heal'], stock: 40 },
            { name: 'Fusidic Acid Cream', brands: ['Fucidin', 'Fudic'], stock: 50 },
        ],
    },
    {
        email: 'owner13@apollothy3.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Amit Kumar',
        displayName: 'Amit K.',
        storeName: 'Apollo Pharmacy - Himayatnagar',
        address: 'Street Number 5, Himayatnagar, Hyderabad, Telangana 500029',
        location: { lat: 17.4082, lng: 78.4852 },
        inventory: [
            { name: 'Paracetamol 650mg', brands: ['Dolo 650'], stock: 500 },
            { name: 'Atorvastatin 10mg', brands: ['Atorva 10'], stock: 200 },
            { name: 'Metformin 500mg', brands: ['Glycomet 500'], stock: 300 },
            { name: 'Telmisartan 40mg', brands: ['Telma 40'], stock: 150 },
            { name: 'Amlodipine 5mg', brands: ['Amlopres 5'], stock: 250 },
        ],
    },
    {
        email: 'owner14@medplus3.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Pooja Agarwal',
        displayName: 'Pooja A.',
        storeName: 'MedPlus - Tolichowki',
        address: 'Tolichowki Main Road, Hyderabad, Telangana 500008',
        location: { lat: 17.3996, lng: 78.4239 },
        inventory: [
            { name: 'Ondansetron 4mg', brands: ['Emeset 4', 'Vomikind'], stock: 100 },
            { name: 'Loperamide 2mg', brands: ['Imodium', 'Andial'], stock: 130 },
            { name: 'Racecadotril Sachet', brands: ['Zedott', 'Redotil'], stock: 90 },
            { name: 'Probiotics', brands: ['Enterogermina', 'Vizylac'], stock: 160 },
            { name: 'Lactulose Solution', brands: ['Duphalac', 'Looz'], stock: 70 },
        ],
    },
    {
        email: 'owner15@healthfirst.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Nikhil Gowda',
        displayName: 'Nikhil G.',
        storeName: 'HealthFirst Medical - Dilsukhnagar',
        address: 'Dilsukhnagar Main Rd, Hyderabad, Telangana 500060',
        location: { lat: 17.3688, lng: 78.5247 },
        inventory: [
            { name: 'Pregabalin 75mg', brands: ['Lyrica', 'Maxgalin 75'], stock: 85 },
            { name: 'Gabapentin 300mg', brands: ['Neurontin', 'Gabapin 300'], stock: 95 },
            { name: 'Amitriptyline 10mg', brands: ['Tryptomer 10', 'Amline 10'], stock: 120 },
            { name: 'Tramadol 50mg', brands: ['Ultram', 'Contramal'], stock: 0 },
            { name: 'Pregabalin + Methylcobalamin', brands: ['Pregastar Plus', 'Maxgalin M'], stock: 100 },
        ],
    },
    {
        email: 'owner16@newlife.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Fatima Khan',
        displayName: 'Fatima K.',
        storeName: 'New Life Pharmacy - Mehdipatnam',
        address: 'Pillar No 24, Mehdipatnam, Hyderabad, Telangana 500028',
        location: { lat: 17.3879, lng: 78.4452 },
        inventory: [
            { name: 'Phenylephrine + Chlorpheniramine', brands: ['Sinarest', 'Wikoryl'], stock: 200 },
            { name: 'Paracetamol + Caffeine', brands: ['Saridon', 'Anacin'], stock: 300 },
            { name: 'Diclofenac + Paracetamol', brands: ['Voveran Plus', 'Fenak Plus'], stock: 150 },
            { name: 'Rabeprazole + Domperidone', brands: ['Razo-D', 'Happi-D'], stock: 110 },
            { name: 'Calcium Carbonate + Calcitriol', brands: ['Bio-D3 Max', 'Calcicad'], stock: 180 },
        ],
    },
    {
        email: 'owner17@pharmacity.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Vijay Devarakonda',
        displayName: 'Vijay D.',
        storeName: 'PharmaCity - Uppal',
        address: 'Uppal Main Road, Hyderabad, Telangana 500039',
        location: { lat: 17.3984, lng: 78.5583 },
        inventory: [
            { name: 'Carbamazepine 200mg', brands: ['Tegretol', 'Zeptol 200'], stock: 60 },
            { name: 'Levetiracetam 500mg', brands: ['Keppra', 'Levipil 500'], stock: 75 },
            { name: 'Valproic Acid 200mg', brands: ['Depakote', 'Encorate 200'], stock: 50 },
            { name: 'Phenytoin 100mg', brands: ['Dilantin', 'Eptoin 100'], stock: 80 },
            { name: 'Clobazam 10mg', brands: ['Frisium 10', 'Lobazam'], stock: 0 },
        ],
    },
    {
        email: 'owner18@starpharma.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Deepika Reddy',
        displayName: 'Deepika',
        storeName: 'Star Pharmacy - Kompally',
        address: 'NH 44, Kompally, Hyderabad, Telangana 500014',
        location: { lat: 17.5304, lng: 78.4870 },
        inventory: [
            { name: 'Montelukast 10mg', brands: ['Montair 10', 'Romilast 10'], stock: 120 },
            { name: 'Budesonide Inhaler', brands: ['Budecort', 'Pulmicort'], stock: 40 },
            { name: 'Salbutamol Inhaler', brands: ['Asthalin', 'Ventolin'], stock: 60 },
            { name: 'Tiotropium Bromide', brands: ['Tiova', 'Spiriva'], stock: 30 },
            { name: 'Theophylline 400mg', brands: ['Unicontin-E 400', 'Theo-Asthalin'], stock: 50 },
        ],
    },
    {
        email: 'owner19@trustmed.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Imran Baig',
        displayName: 'Imran B.',
        storeName: 'Trust Medical - Charminar',
        address: 'Near Charminar, Hyderabad, Telangana 500002',
        location: { lat: 17.3616, lng: 78.4747 },
        inventory: [
            { name: 'Eyedrops (Refresh Tears)', brands: ['Refresh', 'Systane'], stock: 100 },
            { name: 'Eyedrops (Moxifloxacin)', brands: ['Moxicip', 'Vigamox'], stock: 80 },
            { name: 'Ear Drops (Ofloxacin)', brands: ['Zanocin Ear Drops'], stock: 60 },
            { name: 'Nasal Spray (Xylometazoline)', brands: ['Otrivin', 'Nasivion'], stock: 120 },
            { name: 'Herbal Digestive', brands: ['Pudin Hara', 'Hajmola'], stock: 200 },
        ],
    },
    {
        email: 'owner20@modernmed.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Shilpa Shetty',
        displayName: 'Shilpa S.',
        storeName: 'Modern Medical - LB Nagar',
        address: 'Inner Ring Road, L.B. Nagar, Hyderabad, Telangana 500074',
        location: { lat: 17.3516, lng: 78.5487 },
        inventory: [
            { name: 'Finasteride 1mg', brands: ['Finax', 'Propecia'], stock: 50 },
            { name: 'Minoxidil 5% Solution', brands: ['Rogaine', 'Tugain 5%'], stock: 70 },
            { name: 'Isotretinoin 20mg', brands: ['Accutane', 'Isotroin 20'], stock: 40 },
            { name: 'Tretinoin Cream 0.05%', brands: ['Retino-A', 'A-Ret'], stock: 60 },
            { name: 'Ketoconazole Shampoo', brands: ['Nizoral', 'Ketocip'], stock: 90 },
        ],
    },
    {
        email: 'owner21@peoples.com',
        password_plaintext: 'password123',
        role: 'author',
        fullName: 'Anand Sharma',
        displayName: 'Anand',
        storeName: 'People\'s Pharmacy - Miyapur',
        address: 'Miyapur, Hyderabad, Telangana 500049',
        location: { lat: 17.5097, lng: 78.3695 },
        inventory: [
            { name: 'Sildenafil 50mg', brands: ['Viagra', 'Penegra'], stock: 30 },
            { name: 'Tadalafil 10mg', brands: ['Cialis', 'Tadacip'], stock: 25 },
            { name: 'Dapoxetine 30mg', brands: ['Priligy'], stock: 15 },
            { name: 'Tamsulosin 0.4mg', brands: ['Flomax', 'Urimax'], stock: 50 },
            { name: 'Alprazolam 0.5mg', brands: ['Xanax', 'Anxit 0.5'], stock: 0 },
        ],
    },
    // --- Test Users ---
    {
        email: 'user@test.com',
        password_plaintext: 'password123',
        role: 'user',
        fullName: 'Test User',
        displayName: 'Test',
        searchHistory: ['Dolo 650', 'Apollo Pharmacy - Jubilee Hills'],
    },
    {
        email: 'jane.doe@email.com',
        password_plaintext: 'password123',
        role: 'user',
        fullName: 'Jane Doe',
        displayName: 'Jane D.',
        searchHistory: ['Ibuprofen', 'Montair-LC', 'MedPlus - Gachibowli'],
    },
    {
        email: 'test.user2@example.com',
        password_plaintext: 'password123',
        role: 'user',
        fullName: 'Another User',
        displayName: 'User2',
        searchHistory: [],
    }
];


export const seedInitialData = () => {
    try {
        const users = localStorage.getItem('medifind_users');
        if (!users || JSON.parse(users).length === 0) {
            localStorage.setItem('medifind_users', JSON.stringify(seedUsers));
            console.log('Successfully seeded initial user data for Hyderabad.');
        }
    } catch (e) {
        console.error('Failed to seed data:', e);
    }
};